language: ruby

rvm:
  - 2.0.0

sudo: required

before_script:
  - psql -c 'create database first_to_disclose_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
